-- بعد USE graduation_projects;
-- يضيف مشاريع تجريبية مع صور (picsum)؛ INSERT IGNORE يتخطى إن وُجد نفس id.

INSERT IGNORE INTO `projects` (`id`, `title`, `description`, `department`, `grad_year`, `tech_stack`, `owner_linkedin`, `project_poster`, `project_poster_pdf`, `image_url`, `pdf_file`) VALUES
(1, 'منصة إدارة مشاريع التخرج الجامعية', 'منصة ويب عربية لعرض ومشاركة مشاريع التخرج مع بحث متقدم وتصفية حسب القسم وسنة التخرج ورفع ملفات توضيحية.', 'علوم الحاسب والمعلومات', 2026, 'PHP, MySQL, HTML, CSS, JavaScript', NULL, NULL, NULL, 'https://picsum.photos/seed/gradproj1/800/450', NULL),
(2, 'تطبيق إرشاد أكاديمي بالذكاء الاصطناعي', 'واجهة تساعد الطالب على تلخيص المقررات واقتراح خطة مراجعة حسب الجدول الدراسي مع تذكير بالمواعيد.', 'نظم المعلومات', 2025, 'Python, FastAPI, PostgreSQL, REST', NULL, NULL, NULL, 'https://picsum.photos/seed/gradproj2/800/450', NULL),
(3, 'نظام مراقبة استهلاك الطاقة في المختبرات', 'لوحة تحكم لقراءة أجهزة استشعار وعرض الاستهلاك اليومي وتنبيهات عند تجاوز العتبة.', 'هندسة الحاسب', 2025, 'C++, MQTT, Node.js, Chart.js', NULL, NULL, NULL, 'https://picsum.photos/seed/gradproj3/800/450', NULL),
(4, 'منصة تعلم تفاعلية للبرمجة للمبتدئين', 'دروس قصيرة تمارين فورية وتتبع تقدم المتعلم مع شهادات إتمام بسيطة.', 'علوم الحاسب والمعلومات', 2024, 'React, Firebase, TypeScript', NULL, NULL, NULL, 'https://picsum.photos/seed/gradproj4/800/450', NULL),
(5, 'نظام حجز المواعيد للإرشاد الأكاديمي', 'يسمح للطالب بحجز موعد مع المرشد الأكاديمي وإدارة الجدول من لوحة المرشد.', 'نظم المعلومات', 2026, 'PHP, MySQL, FullCalendar', NULL, NULL, NULL, 'https://picsum.photos/seed/gradproj5/800/450', NULL),
(6, 'تطبيق مكتبة رقمية للمقررات', 'رفع ملخصات وملفات PDF مع تصنيف حسب المقرر والبحث النصي داخل العناوين.', 'علوم الحاسب والمعلومات', 2025, 'Laravel, MySQL, Vue.js', NULL, NULL, NULL, 'https://picsum.photos/seed/gradproj6/800/450', NULL),
(7, 'موقع تعريفي لقسم علوم الحاسب', 'صفحات عن الرؤية والتخصصات وروابط للمشاريع المميزة ونموذج تواصل.', 'علوم الحاسب والمعلومات', 2024, 'HTML, CSS, JavaScript', NULL, NULL, NULL, 'https://picsum.photos/seed/gradproj7/800/450', NULL),
(8, 'نظام إدارة فعاليات الجامعة', 'تسجيل الحضور، الجداول الزمنية، وإشعارات للمسجلين قبل الفعالية.', 'نظم المعلومات', 2026, 'PHP, MySQL, Bootstrap', NULL, NULL, NULL, 'https://picsum.photos/seed/gradproj8/800/450', NULL),
(9, 'تطبيق تتبع عادات الدراسة', 'مؤقت بومودورو وإحصائيات أسبوعية وتذكيرات لطيفة لزيادة التركيز.', 'هندسة البرمجيات', 2025, 'Flutter, Dart, SQLite', NULL, NULL, NULL, 'https://picsum.photos/seed/gradproj9/800/450', NULL),
(10, 'بوابة تقديم طلبات مشاريع التخرج', 'نموذج إلكتروني لرفع الفكرة والمشرف مع حالات الموافقة من الإدارة.', 'علوم الحاسب والمعلومات', 2026, 'PHP, MySQL, Alpine.js', NULL, NULL, NULL, 'https://picsum.photos/seed/gradproj10/800/450', NULL),
(11, 'نظام إدارة مخزون مختبر الحاسب', 'تسجيل الأجهزة والإعارات والصيانة مع تقارير جرد شهرية.', 'هندسة الحاسب', 2024, 'PHP, MySQL', NULL, NULL, NULL, 'https://picsum.photos/seed/gradproj11/800/450', NULL),
(12, 'منصة نقاش جماعي لمقرر مشروع التخرج', 'منتدى بسيط للمجموعات مع مرفقات وإشعارات عند رد المشرف.', 'هندسة البرمجيات', 2025, 'PHP, MySQL, JavaScript', NULL, NULL, NULL, 'https://picsum.photos/seed/gradproj12/800/450', NULL);
